version: '3'
services:
    zoo-1:
        image: zookeeper
        ports:
            - 2181:2181
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo-2:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
    zoo-2:
        image: zookeeper
        ports:
            - 2182:2182
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
    zoo-3:
        image: zookeeper
        ports:
            - 2183:2183
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888 server.3=0.0.0.0:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
    solr:
        image: solr
        hostname: solr-{{.Node.ID}}
        # hostname: solr-{{.Node.ID}}
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            # SOLR_HOST: solr-{{.Node.ID}}
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16
